name: warraq
description: "Bookstore app"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  flutter_decorated_text: ^1.0.14
  flutter_svg: ^2.0.17
  file_picker: ^8.3.5
  image_picker: ^1.1.2
  dartz: ^0.10.1
  dio: ^5.8.0+1
  flutter_screenutil: ^5.9.3
  geolocator: ^13.0.2
  lottie: ^3.2.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.4.0
  flutter_bloc: ^9.0.0
  connectivity_plus: ^6.1.3
  flutter_session_jwt: ^0.0.8
  pretty_dio_logger: ^1.4.0
  get_it: ^8.0.3
  oktoast: ^3.4.0
  bot_toast: ^4.1.3
  # pagination_manager: ^1.0.0
  flutter_clean_architecture: ^6.0.1
  go_router: ^14.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - .env


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
